### ISSUE TITLE
Indicate missing connection / not working state

### ISSUE THREAD

**Issue by svenwiegand** [dahdahm/mattermost-chrome-badge#3]
At first: Thanks for providing this very helpful tiny tool.

One thing I've encountered: From time to time the badge doesn't really seem to be connected to mattermost. I think it's after starting up the browser if mattermost hasn't been opened in some tab. I then need to open a mattermost tab to make the badge work. 

This is okay, but it would be helpful, if the badge would be gray or so, if it doesn't really have a connection, so that I know something needs to be fixed.

**Comment by lemieuxl** [comment]
First, thanks for using the tool.

I'm not sure I quite understand the issue. The current implementation does show a grey icon when _mattermost_ is not open in a tab or you are not logged in. If it is not open in a tab and you click the icon, it will open a new tab for you.

If it's not what you see, please send us a screenshot.

**Comment by svenwiegand** [comment]
Okay, will try to reproduce the issue. Until then lets close it.
